name: Awesome Lint

on:
  push:
    branches:
    - main
  schedule:
  # Run once a week, Sunday at 5:00AM:
  - cron: "0 5 * * 0"

jobs:
  run-lint:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install awesome-lint CLI
        run: npm install -g awesome-lint
        
      - name: Run Awesome Lint
        run: awesome-lint

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: 'mlc_config.json'

